import random

def display_random_tip():
    tips = [
        "Tip: Whenever you gain/lose defence or weapon damage while exploring it is also reflected in the item's description in your inventory.",
        "Tip: If battles ever feel too long, you can toggle 'Skip Battles' in the settings menu.",
        "Tip: You can rest after every exploration",
        "Tip: The slime kindom is really powerful as it allows you to acess the merchant and the blacksmith whenever you wish.", 
        "Tip: If you ever aren't sure about a feature try looking inside the help menu.",
        "Fact: There is around 9000 lines of code in this game.",
        "Tip: Your data saves even after closing the game.",
        "Tip: You have about a 20% chance of getting a merchant each time you explore.",
        "Tip: You will be forced to fight the Howler on day 15.",
        "Tip: The blacksmith is better place to buy your weapons and armor as it is cheaper than the merchant.",
        "Tip: You will lose connection with the slime kingdom after you go to the Swamplands.",
        "Tip: Dont forget to check the help menu if you are ever confused.",
        "Fact: V1 Had 250 lines of code, V2 Had 950, V3 Had 2500, V4 had just under 4000 and V5 has 9000.",
        "Fact: 70% of the code in this game is in the main file.",
        "Fact: There is 16 different files in this game.",
        "Tip: You can play a game of rock paper scissors with the forest merchant by typing 'rps' while talking to him.",
        "Fact: Every event in the forest exploration has a 5% chance of happening.",
        "Tip: Pretty much all events have multiple outcomes. Meaning just because an event is bad once doesn't mean it will be bad again.",
        "Tip: You can rest after each exploration.",
        "Tip: The slime kingdom is really important for the Frozen Peaks as it's way cheaper and you will need to heal a lot.",
        "Tip: Try and always have a potion on you as it could save you from death during an unlucky exploration.",
        "Fact: There has been over 80 bug fixes since V2",
        "Fact: You can type 'debug' in the save menu to enter debug mode.",
        "Tip: You dont need to fight the Baron to fight the Dragon.",
        "Fact: You can check your game stats in the pause menu.",
        "Tip: You can toggle 'Enter to Continue' in the settings menu if you want",
        "Tip: You cant die to the Baron and if you lose you will be reset to 50 Gold.",
        "Tip: Moving through zones quickly is safer than over-staying due to enemy scaling.",
        "Tip: Always try to carry at least one potion, it can be the difference between death and survival.",
        "Fact: There is a enemy in the forest that drops 100 gold.",
        "Tip: The Wooden Spear offers some of the best early-game value compared to most starter weapons.",
        "Tip: Getting armour as early as possible reduces damage taken more than increasing damage output.",
        "Tip: If you can’t afford a sword yet but have decent armour, bows can still be a good option.",
        "Tip: Armour upgrades matter more than damage in the Frozen Peaks.",
        "Tip: Enchants from merchants are best saved for when you have excess gold rather than spent immediately.",
        "Fact: The dragon’s ASCII art took over an hour to create.",
        "Fact: The forest contains the highest number of unique events and the widest variety of outcomes.",
        "Fact: The Frozen Peaks has fewer events than the forest, but they tend to be more complex.",
        "Fact: The stats menu system is one of the oldest features still surviving from the earliest version of the game.",
        "Tip: Some of the words for the genie wishes are 'defence' 'luck' 'health'",
    ]
    return random.choice(tips)