import os

# Update log
def updatelog():
    os.system('cls') # Clear CMD
    print("-----Previous Version: V2-----")
    print("- Added a debugging menu")
    print("- Added a help menu")
    print("- Removed Levels")
    print("- Added wayyy more Forest enemies")
    print("- Balance changes")
    print("- More dialogue")
    print("- Changed starting prologue")
    print("- Added some more dividers between parts of the game")
    print("\n-----Previous Version: V3-----")
    print("- Added the Frozen Peaks and Swamplands area")
    print("- Added a Forest, Frozen Peaks and Swamplands boss")
    print("- Added functionality to defence")
    print("- Added critical hits")
    print('- Added around 20 new events and removed the " You found nothing " (mostly) (for the forest area)')
    print("- Added a game of 21 that you can vs a villagers in for gold (easily accessible in debug menu)")
    print("- Added a simple game of higher or lower to bet gold on (easily accessible in debug menu)")
    print("\n-----Previous Version: V3.1-----")
    print("-Added a game of Rock Paper Scissors")
    print("- Added Enchants... without the effects!!")
    print("\n-----Previous Version: V4-----")
    print("-ADDED THE FROZEN PEAKS!!! with about 20 new events, along with the frozen merchant")
    print("-ADDED WORKING and swapable armour from the merchants!!!")
    print("-Added the SLIME KINGDOM!!!")
    print("-Changed defence rewards to be mostly applied to the current armour instead of the player")
    print("-Added a setting to skip the opening dialogue upon opening the game")
    print("-Added tips above the main menu")
    print("-Your settings now save")
    print("-Reworked meeting Bob and the bounty hunters")
    print("-Reworked the endless road to be easier to escape")
    print("-Added more outcomes to the shrine (along with 2 super rare ones :O)")
    print("-Added a press Enter to continue setting")
    print("-Reworked the help menu to include new features and make it easier to understand")
    print("-The terminal now clears to make it easier to see whats happening")
    print("-Added an intro")
    print("-Nerfed the Elf rewards massively")
    print("-Removed Debug mode from settings")
    print("-The player now starts on day 1 instead of 0")
    print("-Removed strength from the berry event and decreased the odds of the berry being positive")
    print("-New Trap in the forest area")
    print("-Made the falling log trap weaker")
    print("-Tweaked flower event rewards")
    print("-Updated Rock Paper Scissors")
    print("-Updated 21 Game")
    print("-Renamed Coins to Gold in check stats")
    print("\n---Bugs---")
    print("-Fixed game crash when exploring haunted house")
    print("-Fixed one of the haunted house events not finishing")
    print("-Fixed multiple instances of the game not registering an invalid input")
    print("-Fixed Frost Orb from bandit outpost showing rewards incorrectly")
    print("-Fixed the map in the endless road not letting you escape")
    print("-Fixed variables not fully resetting when restarting the game")
    print("-Fixed an issue where the merchant would say you cant afford something after you buy it")
    print("-Fixed multiple instances of the game breaking when entering an invalid number")
    print("-Fixed an event that caused you to fight the same enemy over and over")
    print("-Fixed game not ending if player presses anything other than 1 when dead")
    print("-Fixed the berry event from never running out of berries")
    print("-Fixed the gotten lost event to not end when going left")
    print("-Fixed some spelling issues")
    print("\n-----Previous Version: V4.1-----")
    print("-Enchants now work and can be found in more places")
    print("-Made Enchants buyable from merchants")
    print("-Health potions now store in your inventory and will be used to save you from death")
    print("-Added 2 new events to the Frozen Peaks")
    print("\n---Bugs/Changes---")
    print("-Buffed the Enchants to be more useful")
    print("-Removed 'Check Stats' and made it stay at the top")
    print("-Removed Recommended stats from help menu and added them to the boss fight menu")
    print("-Removed the owned weapons and armour from the stat display")
    print("-Changed the 'Critical Hit!' To be in the center of the attacks not at the top")
    print("-Changed the inventory to be easier to navigate")
    print("-Changed the possible rewards from Frozen Peaks crystal cave event from 5+ or -5 to +7 or -7")
    print("-Changed some events in Frozen Peaks have a higher chance to give health")
    print("-Changed slime kingdom exit from '3' to 'r'")
    print("-Changed the frozen peaks 'storm power' to be set to 0 when escaping the endless storm event")
    print("-Changed the 'Knight RPG' intro")
    print("-Changed the rewards of a potion in the Forest cave event")
    print("-Changed when fighting a boss it will now show your recommended defence alongside health and damage")
    print("-Changed the skip intro setting to be set to true after viewing the intro for the first time")
    print("-Changed so if the enemy is already dead, your companions won't attack")
    print("-Changed the game to load wayy faster")
    print("-Changed the Frozen Peaks merchant to be more common")
    print("-Fixed the enemy and player health going into the negatives")
    print("-Fixed blacksmiths being able to upgrade 'No Armour'")
    print("-Fixed viewing the endless storm map crashing the game")
    print("-Fixed a bug where the potion reward from the Old Lady wouldn't work")
    print("-Fixed not being able to buy armour from the Goblin Tinkerer")
    print("-Fixed health potions not working in Frozen Peaks")
    print("-Fixed not fighting the correct enemy in the cave")
    print("-Fixed auto exiting the blacksmith when buying extra damage")
    print("-Fixed robbing the villager saying +3 defence instead of +2 defence")
    print("-Fixed only being able to upgrade armour once in the entire game")
    print("-Fixed multiple incorrect formattings")
    print("-Fixed the Frozen Peaks wizard event from not working")
    print("\n-----Previous Version: V4.2-----")
    print("-The merchant now always appears on day 5 and 11 in the Forest area")
    print("-The merchant now always appears on day 13 and 19 in the Frozen Peaks area")
    print("-Removed the memory game until V5 as I couldn't get it working to the level I want")
    print("-Added a confirmation to sharpening your sword in the blacksmith")
    print("\n---Bugs/Changes---")
    print("-Added the V2 update log back")
    print("-Added a little bit of enemy scaling in the frozen peaks")
    print("-Added a new tip and fact")
    print("-Added a 1 second delay after 'I hope they aren't nearby' in the forest cave event. So cool right??")
    print("-Added the cost of sharpening your sword next to the option")
    print("-Buffed Lifesteal 3 from 20% to 25% lifesteal")
    print("-Nerfed the health and strength of the forest 'hard' enemies slightly")
    print("-Lowered cloth armour price from 300 to 225 gold")
    print("-Changed the elder yeti event so now you get 3 enchant rolls instead of 1 enchant and 10 weapon damage")
    print("-Changed the animal attack line to be 1 line lower")
    print("-Changed the shrine merchant intro line to be 1 line lower too")
    print("-Changed the bandit outpost difficulty to 'VERY HARD' instead of 'VERY DIFFICULT'")
    print("-Fixed the lost villager event from skipping if entering an incorrect option")
    print("-Fixed not being able to buy armour from the Frozen Peaks blacksmith and merchant (band aid fix)")
    print("-Fixed frozen peaks hermit second to last line")
    print("-Fixed a missing [name here] in both the blacksmiths")
    print("-Fixed both blacksmiths not being able to upgrade armour🤦")
    print("-Fixed the map in the forest endless road")
    print("-Fixed caterpillar princess armour plate reward spelling error")
    print("-Fixed drinking a health potion confirmation not showing while exploring")
    print("-Fixed not being able to afford an enchant book not saying you cant afford it")
    print("-Fixed the Snow Wanderer enchant book not having a number")
    print("-Fixed Snow Wanderer being called Merchant when buying a potion")
    print("\n-----Previous Version: V4.3-----")
    print("-Added lifetime game stats to the settings menu (which save by the way)")
    print("-Added three new weapons, two bows, the 'Compound Bow' and 'Elven Bow' and a new spear, the 'Wooden Spear'")
    print("-Added the 'Elven Bow' to the Kind Elf event in the Forest and the other two to the merchants")
    print("-Added the some small enemy scaling to the Forest enemies")
    print("-Added some colours to the headings of events")
    print("-Updated the 21 Minigame to add 'Easy' 'Medium' and 'Hard' difficulties")
    print("-Combined health and max health into one line in your stats")
    print("\n---Bugs/Changes---")
    print("-HOPEFULLY I've fixed ALL the speeling errors and stuff 🤞")
    print("-Buffed the Kind Elf to give +50 Max Health instead of +30")
    print("-Buffed Snow Wanderer's health crystal")
    print("-Lowered Snow Wanderer's prices to be more affordable")
    print("-Changed resting to increase your max health before your health (I was getting ragebaited by it)")
    print("-Changed the Goblin Tinker's damage upgrade price to a uniform 350 gold but only +2 damage for a Frost Sword instead of +4")
    print("-Changed [Bounty Hunter] to be called [Bounty Hunters]")
    print("-Changed the first line when getting the hidden shrine event to make more sense when getting the moss well")
    print("-Fixed having to press enter twice at the end of exploration when having 'Press Enter to Continue' enabled")
    print("-Fixed enemy health still going into the negatives from companion attacks")
    print("-Fixed the Forest merchant not appearing on day 5 and 11 in some cases")
    print("-Fixed Frozen Peaks enemy scaling not calculating properly and buffed it")
    print("-Fixed the Hunting bow and Eagle Spear not being able to be bought")
    print("-Fixed needing to press 1 instead of enter to buy armour from the Snow Wanderer")
    print("-Fixed Forest merchant Cloth Armour still saying it costs 300 gold despite being 225")
    print("-Fixed the storm power not working properly")
    print("-Fixed not being able to die to being bitten by a snake")
    print("\n-----Current Version: V5-----")
    print("-FINSIHED ALL THE MAIN CONTENT OF THE GAME!!!!")
    print("-ADDED THE FINAL AREA, THE VILLAGE OF KLARE!")
    print("-ADDED A DRAGON BOSSFIGHT AT THE END OF THE GAME!!!")
    print("-Added FULL data saving (settings, stats, player data, world state etc all save now,) (you better not save scum)")
    print("-Added a file that saves error logs (feel free to send them to me)")
    print("-Added a Liars Dice minigame")
    print("-Updated the merchants and inventory so you can see the stats on items before purchase and access your inventory to equip them!")
    print("-Updated the 21 minigame to add an Elite difficulty")
    print("-Added the memory minigame back to the frozen peaks area")
    print("-Added a new Forest event where you can find a Shiny Sword")
    print("-Added a gold earned stat and removed the battles won stat")
    print("-Added a 'health left: ' line in the endless road")
    print("-Added more things for the knight to say after killing an enemy")
    print("-Added 18 total new tips and facts")
    print("-Added a warning the day before you fight a boss")
    print("-Removed the Swamplands from code")
    print("-Removed dungeons and replaced it with 1v1 a rich guy for the 2000 gold instead")
    print("\n---Bugs/Changes---")
    print("-Lots of small balancing changes I dont even want to list out (20+)")
    print("-Added Critical hit chance to the player stat display")
    print("-Updated the intro and removed swamplands from it")
    print("-Changed Dark Witch incorrect input text")
    print("-Shortned the time it takes for the caterpillar princess event to end")
    print("-Changed the wording of option 2 when approaching the lost villager")
    print("-Changed the updatelog to put the newest version at the bottom")
    print("-Fixed not taking damage when 'Skip Battles' is on and using a bow")
    print("-Fixed Critical hit chance being stuck at 2 percent with any sword")
    print("-Fixed the defence and strength swapping event from giving the wrong values")
    print("-Fixed the Middle Aged man event from giving the incorrect reward")
    print("-Fixed the Frozen Peaks wizard event (it was just lowkey not working before AND was OP as heck 👍)")
    print("-Fixed some Caterpillar Princess event issues")
    print("-Fixed level 2, 4, 5 and 6 of the Frozen Peaks storm removing double the intended armour defence")
    print("-Fixed not being able to die from getting your foot stuck in the floor in the haunted house 😊")
    print("-Fixed not dying from the fog event in the endless road, falling into the moss well, bear swiping at you and the creature swinging a knife at you")
    print("-Fixed some logic issues with the Bounty Hunters event")
    print("\n---Item Balance Changes---")
    print("Iron Sword: (21 dmg) -> (17 dmg)")
    print("Iron Sword: (100 gold) -> (125 gold)")
    print("Wooden Spear: (250 gold) -> (220 gold)")
    print("Hunting Bow: (225 gold) -> (180 gold)")
    print("Steel Sword: (43 dmg) -> (35 dmg)")
    print("Steel Sword: (300 gold) -> (450 gold)")
    print("Eagle Spear: (35 dmg) -> (45 dmg)")
    print("Shadow Blade: (145 dmg) -> (125 dmg)")
    print("Iron Armour: (550 gold) -> (500 gold)")  
    print("Titanium Armour: (31 def) -> (26 def)")
    print("Titanium Armour: (2100 gold) -> (2000 gold)")
    print("Health Crystal: (350 gold) -> (250 gold)")
    print("\n-------------------------------------------------------------------------")

if __name__ == "__main__":
    updatelog()
